on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          release-type: node
          package-name: release-please-action
